assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: true
  test: false
instrument: CE06ISSP-SP001-09-CTDPFJ000
stream:
  method: telemetered
  name: ctdpf_j_cspp_instrument
workflow_config:
  schedule: 0 0 * * *
